const toggles = {
  A: { letter: 'A', toggledOn: true },
  B: { letter: 'B', toggledOn: true },
  C: { letter: 'C', toggledOn: true },
  D: { letter: 'D', toggledOn: true },
  E: { letter: 'E', toggledOn: true },
  F: { letter: 'F', toggledOn: true },
  G: { letter: 'G', toggledOn: true },
  H: { letter: 'H', toggledOn: true },
  I: { letter: 'I', toggledOn: true },
  J: { letter: 'J', toggledOn: true },
  K: { letter: 'K', toggledOn: true },
  L: { letter: 'L', toggledOn: true },
  M: { letter: 'M', toggledOn: true },
  N: { letter: 'N', toggledOn: true },
  O: { letter: 'O', toggledOn: true },
  P: { letter: 'P', toggledOn: true },
  Q: { letter: 'Q', toggledOn: true },
  R: { letter: 'R', toggledOn: true },
  S: { letter: 'S', toggledOn: true },
  T: { letter: 'T', toggledOn: true },
  U: { letter: 'U', toggledOn: true },
  V: { letter: 'V', toggledOn: true },
  W: { letter: 'W', toggledOn: true },
  X: { letter: 'X', toggledOn: true },
  Y: { letter: 'Y', toggledOn: true },
  Z: { letter: 'Z', toggledOn: true },
}

export default toggles